version: '2.2'

services:
  frontend:
    image: caiqueerodrigues/almeidas-frontend:latest
    # build: . #PARA BUILDAR LOCAL
    container_name: almeidas-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      API_BACKEND: ${API_BACKEND}
    restart: always